name: Deploy EC2

on: 
  push:
    branches:
      - dev
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Initialize and Apply Terraform using Terragrunt for Dev
      if: github.ref == 'refs/heads/dev'
      run: |
        cd envs/dev
        terragrunt init
        terragrunt apply -auto-approve

    - name: Initialize and Apply Terraform using Terragrunt for Prod
      if: github.ref == 'refs/heads/prod'
      run: |
        cd envs/prod
        terragrunt init
        terragrunt apply -auto-approve
